# fly.toml app configuration file generated for medioa on 2024-06-20T14:07:15+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medioa'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'
  CORS_ALLOW_HEADERS = 'Content-Type,Content-Length,Origin,Authorization'
  CORS_ALLOW_METHODS = 'GET,POST,PUT,DELETE'
  CORS_ALLOW_ORIGINS = 'https://medioa.fly.dev'
  ENVIRONMENT = 'prod'
  HOST = 'https://medioa.fly.dev'
  LOG_LEVEL = 'info'
  LOG_MODE = 'json'
  SHUTDOWN_TIMEOUT = '5s'
  STORAGE_CONTAINER = 'medioa'
  VERSION = '1.0.2'
  UPLOAD_MAX_SIZE_MB = '20'
  DOWNLOAD_EXPIRE = '30'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
